[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  # Option 1 – Disable secret scanning completely
  SECRETS_SCAN_ENABLED = "false"

  # Option 2 – (Better) Only skip scanning these specific keys
  SECRETS_SCAN_OMIT_KEYS = "VITE_APPWRITE_URL,VITE_APPWRITE_PROJECT_ID,VITE_APPWRITE_DATABASE_ID,VITE_APPWRITE_STORAGE_ID,VITE_APPWRITE_USER_COLLECTION_ID,VITE_APPWRITE_POST_COLLECTION_ID,VITE_APPWRITE_SAVES_COLLECTION_ID"
